apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud_name" . }}
data:
  cloudName: {{ include "cloud_name" . | b64enc }}
  clouds.yaml: {{ toYaml .Values | b64enc }}
  {{- if .Values.cacert }}
  cacert: {{ .Values.cacert | b64enc }}
  {{- end }}
type: Opaque
