apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud_name" . }}
  labels:
    # Ensure that the Secret is transferred to the target cluster during a `clusterctl move`
    clusterctl.cluster.x-k8s.io/move: ""
data:
  cloudName: {{ include "cloud_name" . | b64enc }}
  clouds.yaml: {{ toYaml .Values | b64enc }}
  {{- if .Values.cacert }}
  cacert: {{ .Values.cacert | b64enc }}
  {{- end }}
type: Opaque
